# Generated by Django 5.1.15 on 2026-09-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_failed_login_attempts_user_lockout_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital_name',
            field=models.CharField(blank=True, default='', help_text='Associated hospital facility for hospital staff', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='hospital_slug',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Lowercase sanitized hospital username', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hospital', 'Hospital'), ('patient', 'Patient')], default='patient', max_length=15),
        ),
    ]
