# Generated by Django 5.1.15 on 2026-09-18 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_hospital_name_user_hospital_slug_and_more'),
        ('doctors', '0011_hospital_doctor_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Direct linked dynamic hospital facility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='doctors.hospital'),
        ),
    ]
