# Generated by Django 6.0.5 on 2026-07-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='max_capacity',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
