# Generated by Django 6.0.5 on 2026-07-16 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models
import django.utils.timezone


def populate_receipt_ids(apps, schema_editor):
    Appointment = apps.get_model('appointments', 'Appointment')
    for index, appt in enumerate(Appointment.objects.all()):
        # Generate a unique receipt_id for existing appointments
        date_str = django.utils.timezone.localdate().strftime('%Y%m%d')
        suffix = uuid.uuid4().hex[:4].upper()
        appt.receipt_id = f'MC-{date_str}-{index:04d}-{suffix}'
        appt.save(update_fields=['receipt_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_slot_max_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional notes from the patient'),
        ),
        # Step 1: Add receipt_id field without unique=True
        migrations.AddField(
            model_name='appointment',
            name='receipt_id',
            field=models.CharField(blank=True, default='', help_text='Auto-generated receipt ID like MC-20260716-001', max_length=30),
        ),
        # Step 2: Populate unique values for existing rows
        migrations.RunPython(populate_receipt_ids),
        # Step 3: Enforce unique=True
        migrations.AlterField(
            model_name='appointment',
            name='receipt_id',
            field=models.CharField(blank=True, default='', help_text='Auto-generated receipt ID like MC-20260716-001', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Auto-calculated from consultation duration', null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Admin can manually block this slot'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='slot',
            name='max_capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
