# Generated by Django 4.2.30 on 2026-07-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_options_alter_slot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='max_capacity',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
