# Generated by Django 5.1.15 on 2026-09-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_slot_max_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat Amount (₹)')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage value (e.g. 20) or flat amount in ₹', max_digits=8)),
                ('coupon_type', models.CharField(choices=[('first_booking', 'First Booking Special'), ('milestone', 'Loyalty Milestone (Every 5 Bookings)'), ('general', 'General Promo')], default='general', max_length=30)),
                ('required_bookings', models.PositiveIntegerField(default=0, help_text='Minimum prior bookings required')),
                ('max_bookings', models.PositiveIntegerField(blank=True, help_text='Maximum prior bookings allowed (e.g. 0 for first booking only)', null=True)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Max discount cap in ₹', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='appointment',
            name='original_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
