# Generated by Django 5.1.15 on 2026-09-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_coupon_appointment_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, help_text='Age of the visiting patient', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(blank=True, default='', help_text='Name of the patient visiting (Self, Mother, Daughter, etc.)', max_length=150),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(blank=True, default='', help_text='Contact phone number for patient consultation updates', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_relation',
            field=models.CharField(blank=True, default='Self', help_text='Relation to user: Self, Mother, Father, Daughter, Son, Spouse, Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional notes or symptoms from the patient'),
        ),
    ]
