# Generated by Django 5.1.15 on 2026-09-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_patient_age_appointment_patient_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('rescheduled', 'Rescheduled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
