# Generated by Django 5.1.15 on 2026-09-18 17:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_status_alter_slot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash cut-off / deduction retained per policy', max_digits=8),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('hospital', 'Hospital'), ('admin', 'Admin')], default='', help_text='Who initiated the cancellation', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net refund amount credited to patient', max_digits=8),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('full', 'Full 100% Refund'), ('partial', 'Partial Refund (Post Cut-off)'), ('completed', 'Refund Completed')], default='none', max_length=20),
        ),
    ]
