# Generated by Django 5.1.15 on 2026-09-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_cancellation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='op_checked_in',
            field=models.BooleanField(default=False, help_text='Hospital staff marked patient as arrived at OP'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='op_checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Patient star rating (1 to 5)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='review_comment',
            field=models.TextField(blank=True, default='', help_text='Patient review comments and feedback'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
