# Generated by Django 5.1.15 on 2026-09-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_completed_at_appointment_is_reviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Doctor consultation rating (1 to 5)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hospital facility & cleanliness rating (1 to 5)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='management_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hospital management & staff behavior rating (1 to 5)', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Overall average star rating (1 to 5)', null=True),
        ),
    ]
