# Generated by Django 6.0.5 on 2026-07-12 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='afternoon_start',
            field=models.TimeField(default=datetime.time(14, 0), help_text='First afternoon slot time'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='morning_start',
            field=models.TimeField(default=datetime.time(9, 0), help_text='First morning slot time'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slot_interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Minutes between each slot'),
        ),
    ]
