# Generated by Django 6.0.5 on 2026-07-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_add_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(help_text='Comma-separated 3-letter weekday codes, e.g. mon,wed,fri', max_length=100),
        ),
    ]
