# Generated by Django 6.0.5 on 2026-07-16 17:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_available_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short biography shown on the doctor profile page'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_duration',
            field=models.PositiveIntegerField(default=30, help_text='Default consultation duration in minutes (used when creating schedules)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, help_text='Average patient rating (1.0 – 5.0)', max_digits=3),
        ),
        migrations.AddField(
            model_name='doctor',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total number of patient reviews'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='afternoon_start',
            field=models.TimeField(default=datetime.time(14, 0), help_text='Legacy: first afternoon slot time'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(blank=True, default='', help_text='Auto-populated from schedules. Comma-separated 3-letter weekday codes.', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='morning_start',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Legacy: first morning slot time'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slot_interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Legacy: minutes between slots'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('doctor', models.ForeignKey(blank=True, help_text='Leave blank for a global holiday affecting all doctors', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Holiday / Blocked Date',
                'verbose_name_plural': 'Holidays / Blocked Dates',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField(help_text='Block start time, e.g. 09:00')),
                ('end_time', models.TimeField(help_text='Block end time, e.g. 12:00')),
                ('consultation_duration', models.PositiveIntegerField(default=30, help_text='Minutes per appointment slot in this block')),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Weekly Schedule Block',
                'verbose_name_plural': 'Weekly Schedule Blocks',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('doctor', 'day_of_week', 'start_time')},
            },
        ),
    ]
