# Generated by Django 4.2.30 on 2026-07-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_options_doctor_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_duration',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='slot_interval_minutes',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='consultation_duration',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='afternoon_start',
            field=models.TimeField(blank=True, help_text='Legacy: start time for afternoon shift', null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='morning_start',
            field=models.TimeField(blank=True, help_text='Legacy: start time for morning shift', null=True),
        ),
    ]
