# Generated by Django 4.2.30 on 2026-07-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_remove_doctor_consultation_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='afternoon_start',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='morning_start',
        ),
    ]
