# Generated by Django 4.2.30 on 2026-07-19 12:07

from django.db import migrations, models
import doctors.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_remove_doctor_afternoon_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/', validators=[doctors.models.validate_image_size]),
        ),
    ]
