# Generated by Django 5.1.15 on 2026-09-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_doctor_is_active_alter_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_address',
            field=models.CharField(blank=True, default='', help_text='Clinic / hospital street address, chamber, or landmark', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Doctor or clinic contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(blank=True, default='', help_text='Doctor or clinic direct contact phone number', max_length=25),
        ),
        migrations.AddField(
            model_name='doctor',
            name='google_maps_url',
            field=models.URLField(blank=True, default='', help_text='Direct Google Maps link. If left blank, auto-generates search link from address/hospital', max_length=500),
        ),
    ]
