# Generated by Django 5.1.15 on 2026-09-18 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_doctor_clinic_address_doctor_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Lowercase sanitized username slug for hospital staff portal login', max_length=100, unique=True)),
                ('contact_phone', models.CharField(blank=True, default='', help_text='Hospital official contact phone number', max_length=25)),
                ('contact_email', models.EmailField(blank=True, default='', help_text='Hospital official contact email', max_length=254)),
                ('address', models.CharField(blank=True, default='', help_text='Street address, campus, or landmark', max_length=255)),
                ('city', models.CharField(blank=True, default='', help_text='City or metropolitan area', max_length=100)),
                ('state', models.CharField(blank=True, default='', help_text='State or province', max_length=100)),
                ('google_maps_url', models.URLField(blank=True, default='', help_text='Direct Google Maps navigation or location link', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital Facility',
                'verbose_name_plural': 'Hospital Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Associated hospital facility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctors.hospital'),
        ),
    ]
