# Generated by Django 5.1.15 on 2026-09-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_hospital_doctor_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.8, help_text='Average hospital patient rating (1.0 – 5.0)', max_digits=3),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total number of patient reviews for this hospital'),
        ),
    ]
